# Generated by Django 4.2.9 on 2024-02-04 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('optimizer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptimizerData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metrics', models.JSONField(null=True)),
                ('buffers', models.JSONField(null=True)),
                ('filters_metrics', models.JSONField(null=True)),
                ('filters_groups', models.JSONField(null=True)),
                ('sectors', models.JSONField(null=True)),
                ('seniorities', models.JSONField(null=True)),
                ('ratings', models.JSONField(null=True)),
                ('esg_ratings', models.JSONField(null=True)),
                ('countries', models.JSONField(null=True)),
                ('maturities', models.JSONField(null=True)),
                ('tickers', models.JSONField(null=True)),
                ('comparison', models.JSONField(null=True)),
                ('history', models.JSONField(null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='optimizer.optimizerfile')),
            ],
        ),
    ]
